aliyun-oss:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    bucket-url: yourBucketUrl
    base-path: yourBasePath
alipay:
    appid:  2021004144614245
    private-key: MIIEowIBAAKCAQEAgrkdfWuuBAazG5A3Hm5ZOcDHQRouT2d6GqaQqT8dGgSW/cRUglb4lF1HY0s/X1kAPjSbdwTPvE4Psz52XOPb22YipI4KrZrW6vJFklOQU2SIPxXtE8eq8Nsd5cMp0yLgFilqZMlDRApfIubtFct0AiLBMlXgsVlg9siSWh309jqRCLer5c/Md3rHxFuj5fQ/KPUZ0bN05HPsaqHo5xDWk334er+o9Z+V95m2KYh9BKJiWQ3vW2sogXdqXiEUsbDtpTK4YYGgQ/1vQ0QfU/TYu/BQZ73w4D2MglBFxBwstBZbwqDUCAAV+4zS9Qrr90ksXOboFjFfOVUYIHHLT0eaIwIDAQABAoIBAH5h/FnivkXUOFugrTl1lDwa3klZx4YrU8jqWpfWlgsuftBvfQjajs/Z8wfTmzxSrsJ1WAzUkQbMLa+s5wBdp5TRhRK05Sv8tGZHvu1+bt3BJ1xelWv3MZRVM+2MJyai5CVo+xzf3HGu2VXED1lv7wOVmFVS475y3CUbuyr3JXrbqITwk5YIeDxoAkRcjyjTYJvBJoI24TVtRgKnF8XmFO2qYSrY5p5C9pQfj4C8r5f4P7YOP8aLnd8qJqkJ6ks0JHsBX9dmkfq9HbealxOp8c8WUp9w1mKXmlNmDxYz1D4g9y9f8m+ZdnBkuyHkwW+1WUi7RfSNDRnxi5SX5Ble2pkCgYEA96JCDc+OLA9YOonKWOKyCJkoPeLXyfwtYpqc22EFoH0nsY/n1WDFo0wnXluviUIXlhNR+zx+PiG1+u8PJ0Dl/N7glRP2P5PrDCY+KyX3mOSzqUl1j7Jgv5bI5+ZR6co711rEu5/97XElAs9hKFpLhQ4VDb2PBoLn5Ndef+P/j0cCgYEAhyO3eApm2mshxOg/DtBrwRBlq/sWLI+D8RBTS9yveNWup/YcfoYHb0okf89yWbcb0KvNKodjCYetmRGdWJ9MoO7Uc50Y2krt+lH4fiHKl/4nJ8OApF0+Xe+YiUEoluNaEcm3XH/+B2skA5gjeE645BpBtwzvL+e6bN8yQ9rAJEUCgYEA32IYcfrshmRlM5E+3oXJEiaO/ZyXClcY3d0ZaHCSMd8UooFtIbgFMTSuQtk0dP4Q5smQ57D/NK8WSUHDiqZpkX3AW9rBBUM7Ah+xbxz1yI9uXmSszy6bRdkQbNkAxYQwDSmNVK+T0dCCEZHfVBZ4D5PPfDCmR7po069QSM/0plsCgYBBEDgoClIEvOmwROT/O+d1N3DMAYJmh95NdL+12ZV+BtslML/9RohT042JH5Z9jURODjkkTbSoBPPWq31nCqM5JGOTGkK57rNu/oI2MAy7avjtExpfiCkbztxQ0Nc69lEKGWU3msPyTGo1dM03AifQYrfa6tZJ6TZ/bmJj+vDhRQKBgEc2JovPTsOtFDiOZSf+JFysUdQLHqI/DkIP0nCwhT1aAoLBU1nPiXDOm/Qu61zCfsE3yCTr1A2uPwqpYvD4XLlzbOvkosBg8ieBtsK62VLgznAkT/r/2htYxjNBlydsEABABPgzADggfjsGBE7EjeWOAm/2e1JmX4QhiJOW4pD1
    ali-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhgs97iHHZ4193jHQMxj+jHIr5Fdj6hBHerPOzI1vKCpH2iFHZK/v4U7YML5OXILybdq+uHT9p4mi7cNEAHN/R5REYrX8DEbEgmSFmsaY2e81MzLxO0QENkp49nnPmhsberExS2s7gTEBtj4SREL+qk0oPgyD5rcCN4xaDCSBEJtQRtzt5zejaxuJDQA1yFNZlxgiIANsbT9SnNm4PD7d6mrek+wK75xPM4zRvOALryEWJo4smGbAFMMCf5X0VVdS4WOQEmIpyCynBGystG4IylsN0K0QcRtIapMGJczpM5ydKwHTcLLPvKWKPhAzcq8EfK1oTQlWfJFbLX7for8cfwIDAQAB

    
autocode:
    server-model: /model/%s
    server-router: /router/%s
    server: /server
    server-api: /api/v1/%s
    server-plug: /plugin/%s
    server-initialize: /initialize
    root: C:\Code\go\src\github.com\5asp\gin-vue-admin
    web-table: /view
    web: /web/src
    server-service: /service/%s
    server-request: /model/%s/request/
    web-api: /api
    web-form: /view
    transfer-restart: true
aws-s3:
    bucket: xxxxx-10005608
    region: ap-shanghai
    endpoint: ""
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: github.com/veteran-dev/server
    s3-force-path-style: false
    disable-ssl: false
captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0
    open-captcha-timeout: 3600
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
db-list:
    - type: ""
      alias-name: ""
      prefix: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      path: ""
      engine: ""
      log-mode: ""
      max-idle-conns: 10
      max-open-conns: 100
      singular: false
      log-zap: false
      disable: true
email:
    to: xxx@qq.com
    from: xxx@163.com
    host: smtp.163.com
    secret: xxx
    nickname: test
    port: 465
    is-ssl: true
excel:
    dir: ./resource/excel/
hua-wei-obs:
    path: you-path
    bucket: you-bucket
    endpoint: you-endpoint
    access-key: you-access-key
    secret-key: you-secret-key
jwt:
    signing-key: e55a0e81-f243-44aa-b34b-8096cd428963
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
local:
    path: uploads/file
    store-path: uploads/file
mongo:
    coll: ""
    options: ""
    database: ""
    username: ""
    password: ""
    auth-source: ""
    min-pool-size: 0
    max-pool-size: 100
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts:
        - host: ""
          port: ""
mssql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: nendb
    username: root
    password: "6BS@ha!ng11#"
    path: 127.0.0.1
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
oracle:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
pgsql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
qiniu:
    zone: ZoneHuaDong
    bucket: ""
    img-path: ""
    access-key: ""
    secret-key: ""
    use-https: false
    use-cdn-domains: false
redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
sqlite:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
system:
    env: local
    db-type: mysql
    oss-type: local
    router-prefix: ""
    addr: 8888
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: false
    use-mongo: false
    ditu-key: e1450be360f0a3d071631e15f000eb4c
    channel-code: CmdcAli
    poi: 
        - "150202"
        - "150203"
        - "150105"
        - "150501"
    reason:
        - "行程有变，暂时不需要用车"
        - "订单信息有误"
        - "选择了其他交通方式"
        - "其他平台价格更低"
        - "司机信息未更新，担心影响行程"
  

tencent-cos:
    bucket: xxxxx-10005608
    region: ap-shanghai
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: github.com/veteran-dev/server
zap:
    level: info
    prefix: '[github.com/veteran-dev/server]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    max-age: 0
    show-line: true
    log-in-console: true
