// 自动生成模板CityData
package city

import (
	"github.com/veteran-dev/server/global"
)

// 城市数据 结构体  CityData
type CityData struct {
	global.GVA_MODEL
	Name      string `json:"name" form:"name" gorm:"column:name;comment:城市名称;"` //城市名称
	ParentID  int64  `json:"parent_id" form:"parent_id" gorm:"column:parent_id;comment:父ID`
	Pinyin    string `json:"pinyin" form:"pinyin" gorm:"column:pinyin;comment:城市名拼音;"` //城市名拼音
	Suffix    string `json:"suffix" form:"suffix" gorm:"column:suffix;comment:城市区划;`
	Code      string `json:"code" form:"code" gorm:"column:code;comment:城市代码;`
	Initial   string `json:"initial" form:"initial" gorm:"column:initial;comment:首字母;"`   //首字母
	Initials  string `json:"initials" form:"initials" gorm:"column:initials;comment:缩写;"` //缩写字母
	Hot       *bool  `json:"hot" form:"hot" gorm:"column:hot;comment:推荐;"`                //推荐
	Order     int64  `json:"order" form:"order" gorm:"column:order;comment:排序`
	CreatedBy uint   `gorm:"column:created_by;comment:创建者"`
	UpdatedBy uint   `gorm:"column:updated_by;comment:更新者"`
	DeletedBy uint   `gorm:"column:deleted_by;comment:删除者"`
}

// TableName 城市数据 CityData自定义表名 prev_city
func (CityData) TableName() string {
	return "district"
}

type AutoGenerated struct {
	Alphabet []string `json:"alphabet"`
	CityList []struct {
		Idx    string `json:"idx"`
		Cities []struct {
			ID        int     `json:"id"`
			Name      string  `json:"name"`
			Pinyin    string  `json:"pinyin"`
			Latitude  float64 `json:"latitude"`
			Longitude float64 `json:"longitude"`
		} `json:"cities"`
	} `json:"cityList"`
	Recommend []struct {
		Cities []struct {
			ID        int     `json:"id"`
			Name      string  `json:"name"`
			Pinyin    string  `json:"pinyin"`
			Latitude  float64 `json:"latitude"`
			Longitude float64 `json:"longitude"`
		} `json:"cities"`
	} `json:"recommend"`
}

type CityDataList struct {
	Alphabet  []string   `json:"alphabet"`
	Recommend []Cities   `json:"recommend"`
	CityList  []CityList `json:"cityList"`
}

type CityList struct {
	Idx    string   `json:"idx"`
	Cities []Cities `json:"cities"`
}
type Cities struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Pinyin   string `json:"pinyin"`
	ParentID int64  `json:"parentID"`
}
